.TH "Hatchery" 3 "Wed Jun 8 2011" "Version 0.9" "YATD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hatchery \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHatchery\fP (double start_x, double start_y, double start_angle)"
.br
.ti -1c
.RI "\fBBug\fP * \fBspawnBug\fP (QString race, double size)"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour YATD à partir du code source.
