.TH "Water" 3 "Mon Jun 6 2011" "Version 0.9" "YATD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Water \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBProjectile\fP.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBWater\fP (QPointF start, QPointF dest, short int lvl)"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)"
.br
.ti -1c
.RI "QRectF \fBboundingRect\fP () const "
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, QColor color)"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBadvance\fP (int step)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour YATD à partir du code source.
